### ISSUE TITLE
Is it compatible with macOS ?

### ISSUE THREAD

**Issue by hpwxf** [yazgoo/umberbar#30]
I like very much your idea of plugins for alacritty. 
Unfortunately, I followed https://github.com/yazgoo/umberbar#using-it and nothing happens.
Since my environnement is macOS 10.15.7 and Alacritty 9999bd53e148c692cc16cd74b6ff4a9f143fe22f (today's master), I wonder if you tried a config like that or if you know limitations to support this environment.

**Comment by hpwxf** [comment]
I tried to understand how it works / don't work.
I can see that new command "alacritty" (cf https://github.com/yazgoo/umberbar/blob/4a5716264b1088a7abb6c221632b88be4d7a5aaf/src/lib.rs#L555) does not support `position` and `dimensions` (I can find these options in alacritty docs).
If I comment out these two options (probably useful), something start (To do so, I copy `umberbar` project as a local dependency in `myumberbar` directory).
However the result is not yet as good as yours: 
![Capture d’écran 2021-02-26 à 23 40 06](https://user-images.githubusercontent.com/26146722/109362956-3da65e80-788c-11eb-8a1e-df5ee58a5934.png)
NB: I also change font in src/main.rs using `font: "SauceCodePro Nerd Font".to_string()`.

**Comment by yazgoo** [comment]
Hi,

Please try and pull the latest version, it should work without --position and --dimension

**Comment by hpwxf** [comment]
Hi, thank you for your quick answer/commit.

Using a fresh new clone of the latest version, it compiles and runs and something appears.
Unfortunately, the display almost the same (this time, the entire windows is your status bar; no more wide transparent area). 
<img width="888" alt="Capture d’écran 2021-03-01 à 11 34 52" src="https://user-images.githubusercontent.com/26146722/109485665-3ea0e100-7a82-11eb-8dfc-e51ba5b0c4d4.png">

May be my usage in not conform. I don't have time to investigate what happens (bad size, no alacritty console below the bar) but I will test it later.

**Comment by yazgoo** [comment]
I guess I could try and add this to the config https://github.com/alacritty/alacritty/issues/168#issuecomment-364983623

**Comment by yazgoo** [comment]
closing this because stale, please reopen if needed
